const PokemonTypeColourMap = new Map<string, string>([
  ["Normal", "bg-[#aaaa99]"],
  ["Fire", "bg-[#ff4422]"],
  ["Water", "bg-[#3399fe]"],
  ["Electric", "bg-[#ffcc33]"],
  ["Grass", "bg-[#77cc55]"],
  ["Ice", "bg-[#66ccff]"],
  ["Fighting", "bg-[#bb5545]"],
  ["Poison", "bg-[#aa5699]"],
  ["Ground", "bg-[#dcbb55]"],
  ["Flying", "bg-[#8899ff]"],
  ["Psychic", "bg-[#ff5699]"],
  ["Bug", "bg-[#aabb23]"],
  ["Rock", "bg-[#bbaa66]"],
  ["Ghost", "bg-[#7d7cc1]"],
  ["Dragon", "bg-[#7766ee]"],
  ["Dark", "bg-[#775544]"],
  ["Steel", "bg-[#aaaabb]"],
  ["Fairy", "bg-[#ee99ee]"],
]);

export const pokemonTypes = [
  { label: "Normal", value: "Normal" },
  { label: "Fire", value: "Fire" },
  { label: "Water", value: "Water" },
  { label: "Electric", value: "Electric" },
  { label: "Grass", value: "Grass" },
  { label: "Ice", value: "Ice" },
  { label: "Fighting", value: "Fighting" },
  { label: "Poison", value: "Poison" },
  { label: "Ground", value: "Ground" },
  { label: "Flying", value: "Flying" },
  { label: "Psychic", value: "Psychic" },
  { label: "Bug", value: "Bug" },
  { label: "Rock", value: "Rock" },
  { label: "Ghost", value: "Ghost" },
  { label: "Dragon", value: "Dragon" },
  { label: "Dark", value: "Dark" },
  { label: "Steel", value: "Steel" },
  { label: "Fairy", value: "Fairy" },
];

export default PokemonTypeColourMap;
